language: python
python:
  - "3.8"

services:
  - docker

install: skip

script:
  - docker build -t agpranjal/college-attendance:latest .

deploy:
  provider: script
  script: /bin/bash docker_push.sh
  on:
    branch: master
