language: python
python:
  - "3.8"

services:
  - docker

install:
  - docker build -t agpranjal/college-attendance:latest .

script:
  - echo "Docker build successfull"
  - echo "Ready to deploy to dockerhub"

deploy:
  provider: script
  script: /bin/bash docker_push.sh
  on:
    branch: master
